#!/bin/sh
# Emits a self-contained phantom-agent installer to stdout.
#
#   make-install-script.sh <binary> <binary-url> > phantom-agent-install.sh
#
# The emitted script is what ships as the `phantom-agent-install.sh` release asset:
# it downloads <binary-url>, verifies it against the SHA-256 of <binary>
# (pinned here at generation time — the installer runs as root from a network
# download, so it must not take the bytes on faith), installs it to
# /usr/local/bin and loads the launchd daemon. Inside the guest:
#
#   curl -fsSL <url-to>/phantom-agent-install.sh -o /tmp/phantom-agent-install.sh
#   sudo sh /tmp/phantom-agent-install.sh
#
# The release workflow generates the published asset; for local agent
# development, generate one against a binary you serve yourself and point
# `image build --agent-url` at it (see README.md).
set -eu

USAGE="usage: make-install-script.sh <binary> <binary-url>"
BIN="${1:?$USAGE}"
URL="${2:?$USAGE}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

SHA="$(shasum -a 256 "$BIN" | awk '{print $1}')"

cat <<EOF
#!/bin/sh
# phantom-agent installer — generated by make-install-script.sh, do not edit.
# Downloads the agent binary, verifies it against the SHA-256 pinned below,
# and installs it as a launchd daemon. Must run as root inside the VM.
set -eu

AGENT_URL='$URL'
AGENT_SHA256='$SHA'
EOF

cat <<'EOF'

[ "$(id -u)" -eq 0 ] || { echo "agent installer must run as root" >&2; exit 1; }

tmp="$(mktemp /tmp/phantom-agent.XXXXXX)"
trap 'rm -f "$tmp"' EXIT

echo "Downloading $AGENT_URL..."
# A guest that has only just booted may not have finished DHCP, so the first
# connect can fail outright; --retry-connrefused waits that out.
curl -fsSL --retry 10 --retry-delay 5 --retry-connrefused --retry-all-errors \
  --connect-timeout 10 -o "$tmp" "$AGENT_URL"

got="$(shasum -a 256 "$tmp" | awk '{print $1}')"
if [ "$got" != "$AGENT_SHA256" ]; then
  echo "SHA-256 mismatch: expected $AGENT_SHA256, got $got" >&2
  exit 1
fi

# Replacing an existing install: stop the old daemon before swapping the binary.
launchctl unload /Library/LaunchDaemons/com.monk.phantom-agent.plist 2>/dev/null || true

echo "Installing /usr/local/bin/phantom-agent..."
mkdir -p /usr/local/bin
install -m 755 "$tmp" /usr/local/bin/phantom-agent

echo "Starting launchd daemon..."
cat > /Library/LaunchDaemons/com.monk.phantom-agent.plist <<'PLIST'
EOF

cat "$SCRIPT_DIR/com.monk.phantom-agent.plist"

cat <<'EOF'
PLIST
chmod 644 /Library/LaunchDaemons/com.monk.phantom-agent.plist
launchctl load /Library/LaunchDaemons/com.monk.phantom-agent.plist

echo "phantom-agent installed and started"
EOF
